package main

import "embed"

// webFS embeds the bundled client (HTML, CSS, app.js + sourcemap, DFN3 WASM
// and ONNX model). Contents of cmd/wisp/web/ are regenerated by
// `node client/build.mjs` (or `bun client/build.mjs`); the directory is
// gitignored. CI/Docker must run the client build before `go build`.
//
//go:embed web/*
var webFS embed.FS
